### ISSUE TITLE
Typo in sidebar

### ISSUE THREAD

**Issue by tushar-c23** [CoLDorg/coldorg.github.io#1]
There's a typo in the sidebar. The full form of Co.L.D. states "**Code. Learn. Develop**" instead of "**Code. Learn. Discuss.**"
![image](https://user-images.githubusercontent.com/92353428/211325838-a413ba12-158e-43e8-a24c-b774d4f17888.png)

**Comment by dravadhis** [comment]
Hi Tushar.
Thanks for notifying the issue. It has been fixed now.

Regards
Shubham
